# Generated by Django 4.0.6 on 2022-07-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='cantidad',
            new_name='cantidad_de_productos',
        ),
    ]
